"""initial schema

Revision ID: 1df637c7f6bb
Revises: 
Create Date: 2026-07-08 10:43:50.595131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df637c7f6bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_label', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('extracting', 'cropping', 'rotation_review', 'duplicate_review', 'complete', name='batch_status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'reviewer', name='user_role'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('r2_key_raw', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('side', sa.Enum('front', 'back', name='scan_side'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'cropped', 'crop_failed', name='scan_status'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_scan_id', sa.Integer(), nullable=False),
    sa.Column('r2_key_cropped', sa.String(), nullable=True),
    sa.Column('crop_bbox', sa.JSON(), nullable=True),
    sa.Column('aspect_ratio_ok', sa.Boolean(), nullable=True),
    sa.Column('rotation_degrees', sa.Integer(), nullable=False),
    sa.Column('rotation_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash_0', sa.String(), nullable=True),
    sa.Column('hash_90', sa.String(), nullable=True),
    sa.Column('hash_180', sa.String(), nullable=True),
    sa.Column('hash_270', sa.String(), nullable=True),
    sa.Column('color_sig_0', sa.JSON(), nullable=True),
    sa.Column('color_sig_90', sa.JSON(), nullable=True),
    sa.Column('color_sig_180', sa.JSON(), nullable=True),
    sa.Column('color_sig_270', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['raw_scan_id'], ['raw_scans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_scan_id')
    )
    op.create_table('duplicate_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_crop_id_a', sa.Integer(), nullable=False),
    sa.Column('card_crop_id_b', sa.Integer(), nullable=False),
    sa.Column('structural_score', sa.Float(), nullable=True),
    sa.Column('color_score', sa.Float(), nullable=True),
    sa.Column('filename_match', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed_duplicate', 'rejected', name='duplicate_status'), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['card_crop_id_a'], ['card_crops.id'], ),
    sa.ForeignKeyConstraint(['card_crop_id_b'], ['card_crops.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('duplicate_candidates')
    op.drop_table('card_crops')
    op.drop_table('raw_scans')
    op.drop_table('users')
    op.drop_table('batches')
    # ### end Alembic commands ###
